name: aws-autodeploy-workflow
on:
  issues:
    types:
      - labeled
jobs:
  aws-autodeploy-workflow:
    if: startsWith(github.event.label.name, 'action-')
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      # Setup terraform (only needed for action-deploy and action-delete)
      - name: Terraform
        uses: hashicorp/setup-terraform@v3
        if: github.event.label.name == 'action-deploy' || github.event.label.name == 'action-delete' || github.event.label.name == 'action-recover'
      
      # run aws_autodeploy.rb
      - name: Run main action
        id: run-aws-autodeploy-action
        working-directory: ./src
        if: github.event.label.name == 'action-validate' || github.event.label.name == 'action-deploy' || github.event.label.name == 'action-update' || github.event.label.name == 'action-delete' || github.event.label.name == 'action-purge' || github.event.label.name == 'action-recover'
        shell: bash
        run: |
          ruby aws_autodeploy.rb ${{ github.event.label.name}} ${{ github.event.issue.number }}